[login]
name = "example"
login_url = "https://aunicalogin.polimi.it/aunicalogin/getservizio.xml?id_servizio=2299"
username = "10560276"
password = "Expedition33"
totp_secret = "V2R6KCEQBU57OZGNW2P46ILZ4NZCYTI2"

[login.selectors]
username = "input#login"
password = "input#password"
submit = ".aunicalogin-button-accedi > button"
otp = "input#otp"
otp_submit = "#submit-dissms"
saml_response = "input[name='SAMLResponse']"

[[profiles.accounts]]
label = "jedi_test"
iam-role = "polimi-framework-developer"
saml-provider = "idp-polimi"
account = "562324089431"

[[profiles.accounts]]
label = "jedi_prod"
iam-role = "polimi-framework-developer"
saml-provider = "idp-polimi"
account = "108034374417"

[[profiles.accounts]]
label = "jedi_dev"
iam-role = "polimi-framework-developer"
saml-provider = "idp-polimi"
account = "263336852471"
